name: ss-craper

channels:
  - conda-forge

dependencies:
  - python=2.7
  - bokeh
  - numpy
  - pandas
  - blaze
  - flask
  - scrapy
  - unidecode
  - pip:
    - mongoengine
    - dictdiffer
    - flask_nav
    - flask_bootstrap
    - flask_wtf
    - flask_appconfig
    - flask_cache
